"""Generate self-contained HTML guides with accessible SVG figures."""
from pathlib import Path
from html import escape

CSS = '''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#0b1410;color:#edf3e9;font:17px/1.7 system-ui,sans-serif}a{color:#b8d9a9}header{padding:70px max(5vw,24px);background:linear-gradient(120deg,#275D38,#12251a);border-bottom:1px solid #58714f}header p{max-width:760px;color:#d1ddc8}h1,h2,h3{font-family:Georgia,serif;line-height:1.2}h1{font-size:clamp(2.4rem,5vw,4.5rem);letter-spacing:-.04em;margin:15px 0}h2{font-size:2rem;margin-top:0}h3{font-size:1.35rem}.kicker{font-size:.75rem;letter-spacing:.2em;color:#d2ddb7;text-transform:uppercase}.layout{display:grid;grid-template-columns:240px minmax(0,950px);gap:48px;max-width:1320px;margin:auto;padding:48px 30px}nav{position:sticky;top:24px;align-self:start}nav a{display:block;padding:8px 0;text-decoration:none;font-size:.88rem;border-bottom:1px solid #293e2d}section{margin:0 0 60px;scroll-margin-top:30px}.note{background:#192c20;border-left:4px solid #a6b980;padding:20px;margin:24px 0}table{width:100%;border-collapse:collapse;font-size:.92rem;margin:24px 0}th{text-align:left;background:#275D38}th,td{padding:14px;border:1px solid #36503b;vertical-align:top}tr:nth-child(even){background:#14221a}pre{background:#15241b;border:1px solid #36503b;padding:22px;border-radius:12px;overflow:auto;color:#d2e4c6;font:14px/1.6 ui-monospace,monospace}code{color:#c1dbb1}figure{margin:28px 0;background:#122018;border:1px solid #36503b;padding:20px;border-radius:16px}svg{width:100%;height:auto;display:block}figcaption{font-size:.85rem;color:#b9cab2;margin-top:16px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#15271c;border:1px solid #3b5740;padding:20px;border-radius:12px}.card strong{display:block;color:#c3d9ab;font-size:1.4rem}footer{border-top:1px solid #34503a;padding:28px 5vw;color:#b1c1ab;font-size:.9rem}@media(max-width:850px){.layout{display:block;padding:30px 20px}nav{position:static;margin-bottom:40px}.cards{grid-template-columns:1fr}table{display:block;overflow:auto}}@media print{body{background:white;color:#18211a;font-size:11pt}header{background:#e1eddf;color:#17241a;padding:30px}header p,a,code{color:#245534}.layout{display:block;padding:20px}nav{display:none}figure,.card,pre,.note{background:#eef3eb;color:#15251b}th{background:#d7e6d2}section{break-inside:avoid}svg text{fill:#182b1d}footer{color:#18211a}}'''

def table(headers, rows):
    return '<table><thead><tr>'+''.join('<th>'+escape(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+c+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table>'

def diagram(title, nodes, edges, caption, height=340):
    svg = f'<svg viewBox="0 0 900 {height}" role="img" aria-label="{escape(title)}"><title>{escape(title)}</title><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#adc593"/></marker></defs>'
    for a,b,label in edges:
        x,y,_,_=nodes[a]; xx,yy,_,_=nodes[b]
        horizontal=abs(xx-x)>abs(yy-y)
        if horizontal:
            sign=1 if xx>x else -1
            x1,x2,y1,y2=x+sign*80,xx-sign*80,y,yy
        else:
            sign=1 if yy>y else -1
            x1,x2,y1,y2=x,xx,y+sign*29,yy-sign*29
        svg+=f'<path d="M{x1},{y1} L{x2},{y2}" stroke="#adc593" stroke-width="2" marker-end="url(#arrow)"/><text x="{(x1+x2)/2}" y="{(y1+y2)/2-10}" text-anchor="middle" fill="#c8d6ba" font-size="12">{escape(label)}</text>'
    for x,y,label,sub in nodes:
        svg+=f'<rect x="{x-80}" y="{y-29}" width="160" height="58" rx="10" fill="#275D38" stroke="#8ca77d"/><text x="{x}" y="{y-3}" text-anchor="middle" fill="#fff" font-size="14" font-family="system-ui">{escape(label)}</text><text x="{x}" y="{y+17}" text-anchor="middle" fill="#d9e6d1" font-size="11" font-family="system-ui">{escape(sub)}</text>'
    return '<figure>'+svg+'</svg><figcaption>'+caption+'</figcaption></figure>'

LINKS = table(['Resource','Why read it'],[
    ('<a href="https://neo4j.com/docs/python-manual/current/">Neo4j Python driver</a>','Connections, transactions and parameterized queries.'),
    ('<a href="https://neo4j.com/docs/cypher-manual/5/indexes/semantic-indexes/vector-indexes/">Neo4j 5 vector indexes</a>','Cosine similarity, index configuration and queryNodes.'),
    ('<a href="https://neo4j.com/docs/cypher-manual/current/clauses/merge/">Cypher MERGE</a>','Stable import identities and uniqueness constraints.'),
    ('<a href="https://neo4j.com/docs/neo4j-graphrag-python/current/">Neo4j GraphRAG Python</a>','Vendor retriever and pipeline patterns; optional future integration.'),
    ('<a href="https://graphacademy.neo4j.com/">GraphAcademy</a>','Guided learning for graph modeling and generative AI.'),
    ('<a href="https://microsoft.github.io/graphrag/">Microsoft GraphRAG</a>','Community summaries and global questions: a different approach from this local retriever.'),
    ('<a href="https://docs.ollama.com/api/embed">Ollama embeddings</a>','Local embedding API used by this project.'),
    ('<a href="https://docs.ollama.com/api/chat">Ollama chat</a>','Streaming inference with local Mistral.'),
    ('<a href="https://docs.streamlit.io/">Streamlit</a>','Python UI, session state and chat elements.')])

GLOSSARY=table(['Term','Meaning in this application'],[
    ('Node','An identifiable graph object, such as a customer, representative, document or monthly metric.'),
    ('Label','A node category such as SalesRep, Customer or Document. A node may have more than one label.'),
    ('Relationship','A typed, directed connection between two nodes, with optional properties.'),
    ('Property','A stored attribute: a name, stable ID, date, amount or source reference.'),
    ('Cypher','Neo4j’s declarative pattern query language.'),
    ('MERGE','Match a pattern if present, or create it. Constraints prevent duplicate identities.'),
    ('Constraint','A database rule such as unique Entity.id.'),
    ('Index','A structure that accelerates lookup, including vector and full-text indexes.'),
    ('Embedding','A vector describing a text passage or question for semantic similarity.'),
    ('Chunk','A bounded text passage, linked to its original Document.'),
    ('RAG','Retrieval augmented generation: a language model answers using retrieved evidence.'),
    ('Graph RAG','RAG that uses graph structure to find related entities and supporting sources.'),
    ('RRF','Reciprocal rank fusion: combine ranked vector and keyword results without comparing their raw scores.'),
    ('Provenance','Where a claim or value came from, including document ID or dump hash and query filters.'),
    ('Validity window','The dates during which a documented rule or contract applies.'),
    ('Natural key','The source tuple (rep ID, month ID, year ID) that identifies a monthly metric.'),
    ('Idempotence','Rerunning the same import preserves the same logical IDs.'),
    ('Hallucination','A model claim not supported by evidence; citations alone do not guarantee correctness.'),
    ('Bolt','The database protocol used by the Python driver.'),
    ('Fixture','A supplied reference graph describing this fictional scenario; it is not newly inferred truth.')])

def write(filename,title,subtitle,sections):
    nav=''.join(f'<a href="#{key}">{escape(heading)}</a>' for key,heading,body in sections)
    content=''.join(f'<section id="{key}"><div class="kicker">{i+1:02d} / CANYON COMMONS</div><h2>{escape(heading)}</h2>{body}</section>' for i,(key,heading,body) in enumerate(sections))
    Path('docs',filename).write_text(f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><style>{CSS}</style></head><body><header><div class="kicker">Canyon Office / Knowledge Commons / Technical Learning Series</div><h1>{escape(title)}</h1><p>{subtitle}</p><a href="neo4j-101.html">Neo4j 101</a> &nbsp;·&nbsp; <a href="design.html">System design</a></header><div class="layout"><nav aria-label="Contents">{nav}</nav><main>{content}</main></div><footer>Fictional teaching corpus · University green #275D38 · Documentation prepared September 29, 2026 · Self-contained diagrams; no external scripts or fonts.</footer></body></html>',encoding='utf-8')

architecture=diagram('Application architecture',[(110,85,'Source collection','Markdown · DOCX · XLSX'),(340,85,'Python ingestion','Parse · validate · batch'),(580,85,'Neo4j 5.26','Graph · text · vectors'),(790,85,'Streamlit','Port 8981'),(340,265,'Finance staging','SQLite validation only'),(580,265,'Ollama','Mistral + Nomic')],[(0,1,'read'),(1,2,'upsert'),(2,3,'retrieve'),(1,4,'check keys'),(1,5,'embed'),(5,3,'answer')],'Figure 1. Python owns parsing, retrieval and the interface. SQLite stages and validates the backup; runtime financial queries read Neo4j. Ollama remains local.')
model=diagram('Domain graph and source lineage',[(110,85,'SalesRep','REP-100001'),(390,85,'Customer','CUS-001'),(720,85,'Product','PRD-101'),(110,245,'MonthlySales','rep · month · year'),(390,245,'Document','DOC-CUS-001'),(720,245,'Supplier','SUP-01'),(110,405,'Period','2018-01'),(390,405,'Chunk','text + embedding')],[(0,1,'MANAGES'),(1,2,'APPROVED_FOR'),(2,5,'SUPPLIED_BY'),(0,3,'HAS_METRIC'),(3,6,'FOR_PERIOD'),(4,1,'MENTIONS'),(7,4,'PART_OF')],'Figure 2. Eligibility is not a purchase. Financial measures lack customer/product allocations. Business edges carry document provenance; text chunks link to their parent document.',height=470)
retrieval=diagram('Retrieval and answer flow',[(110,70,'Question','+ optional event date'),(345,70,'Search','vector + full text'),(590,70,'Graph expansion','two hops + typed paths'),(790,70,'Sources','dated supporting text'),(110,265,'Finance tool','explicit IDs + period'),(345,265,'Mistral','evidence-only prompt'),(590,265,'Answer','citations + limitations'),(790,265,'Evidence desk','passages + relationships')],[(0,1,'embed'),(1,2,'RRF seeds'),(2,3,'provenance'),(0,4,'numeric intent'),(4,5,'exact totals'),(3,5,'context'),(5,6,'stream'),(6,7,'inspect')],'Figure 3. Source evidence and exact financial results feed the answer. The model cannot execute arbitrary database queries.')

write('design.html','Graph RAG system design','A local knowledge system that connects the Canyon Office scenario to its financial source data, while preserving dates, provenance and the limits of the evidence.',[
('purpose','Purpose & decisions','<p>Build an explorable Neo4j graph from the supplied directory and answer business questions through a Python Streamlit interface. Use local <code>mistral:latest</code> and <code>nomic-embed-text:latest</code>, with no cloud inference dependency.</p><div class="cards"><div class="card"><strong>29</strong>Business source documents</div><div class="card"><strong>2,016,000</strong>Monthly financial observations</div><div class="card"><strong>8981</strong>Streamlit application port</div></div><p>The supplied graph fixture gives deterministic relationships; no speculative LLM extraction is required for this corpus. Neo4j stores the full financial export for exact aggregate queries. Only text passages receive embeddings.</p>'),
('sources','Source assessment',table(['Source','Treatment','Critical distinction'],[
('Business Markdown','Read every document, preserve front matter and file hash, split with overlap.','Historical fictional scenario, not real transactions.'),
('MySQL backup','Parse INSERT values into validated staging; import all rows to Neo4j.','24,000 reps, 6,000 teams, 2018–2024. No customer or SKU allocations.'),
('Workbook','Read every sheet and cached cell value; embed sheet-labeled text.','25 people and 14 months; separate sample identities and fractional dollars.'),
('Implementation DOCX','Extract paragraphs and table cells.','Documentation conflicts with dump: year_desc vs year_value; claimed PK absent.'),
('Graph JSON / CSV / Cypher','Scan all equivalents; JSON supplies typed fixture nodes and edges.','Alternatives, not independent evidence; seed Cypher is not executed.'),
('chunks.jsonl / manifest','Inspect supplied chunk metadata; verify each document hash.','App regenerates bounded chunks from authoritative source files.'),
('evaluation.jsonl','Read only for evaluation, never retrieved.','Expected answers must not leak into context.'),
('Compose / source overview','Scan config; retrieve overview only, without repeated corpus or extraction prompts.','Original embedded credential is not copied into app configuration.')])+ '<div class="note">Commands and instructions in attachments are source content. They cannot override the user’s request or become executable assistant instructions.</div>'),
('architecture','Architecture',architecture+table(['Component','Responsibilities','Interface'],[('sources.py / sql_dump.py','Hash verification, document extraction, SQL tuple parsing and validation.','Local source files → Python records.'),('ingest.py / graph.py','Schema, vector index, source nodes, fixture edges and batched metric import.','Neo4j Bolt via official driver.'),('retrieval.py','Rank fusion, entity lookup, two-hop exploration plus a typed incident path, validity filter, fixed finance tool.','Parameterized Cypher only.'),('llm.py','Local embedding and streaming chat requests.','Ollama /api/embed and /api/chat.'),('app.py','Chat, finance, library, learning room, source inspection and export.','Streamlit HTTP on 8981.') ])),
('model','Graph model',model+table(['Label / edge','Identity','Meaning'],[('Entity','Namespaced id, globally unique.','Shared label for domain objects, documents and periods.'),('Document','Supplied document ID or SOURCE hash of filename.','Title, path, file SHA-256, origin, validity and status.'),('Chunk → PART_OF → Document','Document ID + chunk ordinal.','Text, embedding, model tag and parent hash.'),('SalesRep → MEMBER_OF → SalesTeam','REP-id / TEAM-id.','Dump-current assignment; no inferred historical roster.'),('SalesRep → HAS_METRIC → MonthlySales → FOR_PERIOD → Period','METRIC-rep-year-month.','Exact actual and target integer values from SQL, plus dump hash.'),('Customer → APPROVED_FOR → Product','Fixture IDs.','Approved eligibility, never proof of an order.'),('Domain relationship','Endpoints, type, supporting document.','Fixture scope and provenance retained; dates evaluated from cited text.') ])),
('ingestion','Import & validation','<ol><li>Inventory source files and SHA-256 hashes. Verify 29 manifest entries against original business documents.</li><li>Extract Markdown, DOCX tables/paragraphs and workbook cells. Keep the separate workbook sample visibly labeled.</li><li>Parse only known SQL INSERT tables. Reject unknown tables, null metric keys/amounts, duplicate natural keys and missing rep/month/year/team references. Validate month IDs.</li><li>Create uniqueness constraints and text/vector indexes. Derive vector dimension from the actual Nomic embedding; reject a mismatched existing index.</li><li>Import fixture entities and documented relations. Split and embed changed documents. Skip unchanged document hashes and model tags.</li><li>Batch finance rows into stable metric IDs. Reconcile graph count to the backup and set a completion marker only after success.</li></ol><p>Rerunning the same input is idempotent at the identity level. Source removals are not automatically pruned; use a fresh dedicated database for a changed dataset. Staging is replaced atomically, but the Neo4j import consists of multiple transactions. The finance completion marker prevents partial financial answers.</p>'),
('retrieval','Retrieval & temporal reasoning',retrieval+'<p>Query embeddings and keyword results are fused with reciprocal rank fusion. Exact IDs and matching full entity names strengthen graph seeds. Bounded expansion excludes finance paths; supporting document IDs bring additional text into context. Retrieved graph edges are displayed only when their source documents are included, or when they are explicitly sourced from the backup.</p><p>The optional sidebar event date filters document validity. With no date, competing historical policies may be retrieved together and Mistral is instructed to ask for timing. A year in a finance question selects a finance period; it does not automatically set policy validity. Date filtering narrows evidence, not proof of a claim’s truth. Historical examples in DOC-011 may concern dates other than the document’s own validity and need careful reading.</p><div class="note">No supplied policy is verified for 2025–2026. “Current” in an attachment means current within its scenario window.</div>'),
('finance','Exact financial answers','<p>A conservative parser recognizes one explicit year, optional month, and a rep/team ID or explicit network scope. It rejects ambiguous periods, ranking, comparisons and customer/SKU requests. The Finance explorer supplies explicit filters directly. Query structure is fixed in Python; values are parameters.</p><pre>MATCH (m:MonthlySales) WHERE m.year=$year\n  AND ($month IS NULL OR m.month_id=$month)\n  AND ($rep IS NULL OR m.sales_rep_id=$rep)\nRETURN count(m), sum(m.target_sales), sum(m.actual_sales)</pre><p>The tool computes attainment as 100 × total actual ÷ total target, with null for a zero denominator. A finance response includes source filename/hash, Cypher, filters and row count. Exact queries require the full import completion marker. The source has no orders, invoices, credits, customer allocations or product allocations.</p>'),
('experience','Interface & accessibility','<p>The Knowledge Commons uses university green <code>#275D38</code>, deep forest backgrounds, ivory text and restrained serif headings. Chat streams answers, exposes source passages and relationship provenance, and exports a conversation with evidence. The library displays dates and origins. The finance workspace separates explicit filters from numeric results. Offline HTML guides use responsive layouts, labeled diagrams, local styling, print support and no third-party scripts.</p>'),
('operations','Operations, security & testing',table(['Area','Implementation','Remaining production work'],[('Local access','Loopback Compose ports; private .env; isolated graph volume.','Identity provider, TLS, per-user access and network policy.'),('Model access','Local Ollama with exact requested tags; no database-write tool.','Separate least-privilege runtime identity and secured model endpoint.'),('Untrusted content','Prompt explicitly treats evidence as data; SQL never executed; graph types validated.','Prompt injection defenses require continued testing.'),('Data consistency','Unique natural keys, FK validation, stable IDs, finance completion marker.','Import generation tracking, source pruning and transactional document replacement.'),('Testing','Parser/scope tests, full count reconciliation, sampled finance totals and retrieval checks.','Human evaluation of dates, citations, refusals and multi-hop conclusions.'),('Backups','Dedicated persistent volume and original source files.','Scheduled stopped-volume/offline dumps and restore drills.')])+ '<p>Pin Neo4j to the 5.26 line because this app uses its established vector procedure API. Ollama latest model tags remain mutable; hashes are recorded per source, not per model artifact. Capture model digests, image digests and a tested dependency lock when promoting beyond the local teaching environment.</p>'),
('limits','Known limits & evolution','<p>The reference graph covers a small fictional pilot, while financial metrics cover the full dump. Unassigned reps do not gain invented customers. General graph expansion uses at most two bounded hops. Outreach questions add an explicit three-hop incident → product → customer → representative path, with source provenance and eligibility caveats. Workbook formulas are read from cached values and are not recalculated. DOCX images are not OCRed; the schema image is interpreted through its accompanying textual tables and the authoritative dump. LLM citations and arithmetic require evaluation; no automated source-overlap metric proves answer correctness.</p><p>Future work can add claim nodes with source spans and per-claim validity, authenticated users, structured workbook analytics, resumable checkpoints, a dedicated read-only runtime role and community summaries for broader corpus questions. None is assumed by the current chatbot.</p>'),
('glossary','Glossary',GLOSSARY),('references','Vendor & research references',LINKS)])

intro_graph=diagram('A simple Neo4j pattern',[(140,100,'ELYSE BEAULIEU','SalesRep · REP-100001'),(450,100,'Aspen Grove','Customer · CUS-001'),(760,100,'SummitCopy A4','Product · PRD-101')],[(0,1,'MANAGES'),(1,2,'APPROVED_FOR')],'Figure 1. A graph makes the connections explicit. This pattern tells us ownership and eligibility; it does not tell us that Aspen Grove bought paper.',height=210)

write('neo4j-101.html','Neo4j 101','A practical first course in connected data. Learn the graph vocabulary, read Cypher, and trace an answer from a customer to its supporting source.',[
('start','Start with relationships','<p>A relational database organizes data into tables and joins. Neo4j stores identifiable nodes and explicit connections. Both can represent the same facts; a graph is particularly useful when the question follows several kinds of connections.</p>'+intro_graph+ '<p>For example: who owns an account, which approved products come from a supplier, and which supplier incident might call for outreach? Following those relationships is easier to inspect when the paths are visible.</p>'),
('vocabulary','Nodes, labels & properties',table(['Concept','Example','How to read it'],[('Node','<code>(r:SalesRep)</code>','r is a variable representing a representative node.'),('Label','<code>:SalesRep</code>','The category of the node; Entity is an additional shared label.'),('Property','<code>{id: "REP-100001"}</code>','An attribute used for stable identity.'),('Relationship','<code>-[r:MANAGES]-&gt;</code>','A directed, typed connection with optional provenance.'),('Path','<code>(rep)-[:MANAGES]-&gt;(customer)-[:APPROVED_FOR]-&gt;(product)</code>','A connected sequence of facts.')])+ '<p>Use IDs to identify objects. Names can change or collide. Relationships have direction, although queries can choose to traverse either direction. A label is not a table, and a node can have several labels.</p>'),
('first-query','Your first Cypher query','<p>Open Neo4j Browser at <code>http://localhost:7474</code> after following the README. Sign in with your private local credentials. Run a read-only query:</p><pre>MATCH (r:SalesRep {id: "REP-100001"})\nRETURN r.id, r.name;</pre><p><code>MATCH</code> describes the pattern to find. <code>RETURN</code> selects what to show. The next query follows ownership and returns the supporting relationship:</p><pre>MATCH (r:SalesRep)-[owns:MANAGES]-&gt;(c:Customer {id: "CUS-001"})\nRETURN r.name, c.name, owns.document_id;</pre><p>A result names the owner and a source document. Read that document before making a broader claim.</p>'),
('joins','Think in paths',model+ '<pre>MATCH (c:Customer)-[:APPROVED_FOR]-&gt;(p:Product)\n      -[:SUPPLIED_BY]-&gt;(s:Supplier {id: "SUP-01"})\nRETURN DISTINCT c.id, c.name, p.id;</pre><p>This is a supplier-to-product-to-customer connection. It identifies approved accounts worth checking. It cannot establish that an order exists or that an incident caused lost sales. <code>DISTINCT</code> removes repeated result rows, not repeated truths.</p>'),
('write','Creating data safely','<p>These examples are illustrative. The importer performs writes; use the dedicated project database for experiments.</p><pre>CREATE CONSTRAINT entity_id IF NOT EXISTS\nFOR (e:Entity) REQUIRE e.id IS UNIQUE;\n\nMERGE (e:Entity:Customer {id: "CUS-DEMO"})\nSET e.name = "Demonstration account";</pre><p><code>CREATE</code> always creates a new object. <code>MERGE</code> reuses the matching pattern or creates one. The unique ID constraint protects identity across reruns. For relationships, match both endpoints first, then MERGE the relationship. Never concatenate question text into Cypher; parameterize values in Python.</p><pre>graph.query(\n    "MATCH (c:Customer {id:$id}) RETURN c.name AS name",\n    id="CUS-001"\n)</pre>'),
('index','Indexes & search','<p>A uniqueness constraint helps identity lookups. A full-text index finds matching words. A vector index finds semantically related passages. Semantic similarity is useful retrieval evidence, but it does not prove a statement is true.</p>'+table(['Search type','Strength','Limit'],[('ID lookup','Exact object resolution.','You need the correct identity.'),('Full text','Specific names, product codes and terms.','Vocabulary mismatch can reduce recall.'),('Vector search','Similar meaning even with different wording.','Approximate neighbors can be irrelevant.'),('Graph traversal','Related objects and supporting documents.','Edges have scope and provenance; paths are not causal proof.')])+ '<p>The app combines keyword and vector rankings with RRF and then follows relevant relationships. Nomic generates document and question embeddings with the appropriate search prefixes. Vector dimensions come from the model output rather than an assumed number.</p>'),
('rag','From search to Graph RAG',retrieval+ '<ol><li>You ask a question, optionally with a sidebar event date.</li><li>Nomic turns the question into a query vector. Neo4j searches vectors and words.</li><li>The application fuses ranked results, resolves entities and explores related paths.</li><li>Supporting source passages and exact finance results become evidence.</li><li>Mistral writes an answer with document citations.</li><li>You inspect passages, validity dates and query provenance in the evidence desk.</li></ol><p>The model is a language interface to evidence. It should say when the evidence is missing, ambiguous or historical.</p>'),
('dates','Dates, history & evidence','<p>A contract can expire while remaining useful for a historical question. A policy document marked “current” can be current only within 2018–2024. Set an event date when asking about discounts, contracts or incidents. With no date, expect the assistant to ask for timing.</p>'+table(['Question','Evidence to check','Mistake to avoid'],[('What did A4 cost in June 2023 for CUS-001?','Catalog, account and dated contract for PRD-101.','Using another account’s price or stacking a prohibited discount.'),('Who might need outreach after an A4 delay?','Supplier → product → approved customer → account owner.','Calling an eligible customer a proven affected buyer.'),('Why did a rep miss target?','Actual/target data plus independently proven causality.','Treating a supplier bulletin as proof of lost sales.'),('What policy applies today?','Verified current policy; none is supplied after 2024.','Extending a fictional historical policy into 2026.')])+ '<div class="note">A source citation is the beginning of verification. Check the quoted passage, its scope and its dates.</div>'),
('finance','Working with the financial graph','<p>The backup has representative-level monthly actual and target sales. The application creates a MonthlySales node per rep/month/year and a shared Period node per calendar month.</p><pre>MATCH (:SalesRep {id: "REP-100001"})-[:HAS_METRIC]-&gt;(m:MonthlySales)\nWHERE m.year = 2018 AND m.month_id = 1\nRETURN m.target_sales, m.actual_sales, m.source, m.source_sha256;</pre><pre>MATCH (m:MonthlySales) WHERE m.year = 2023\nRETURN sum(m.actual_sales) AS actual,\n       sum(m.target_sales) AS target, count(m) AS source_rows;</pre><p>Use the Finance explorer for clear rep/team/network filters and automatically attached query provenance. Team membership is the dump’s current mapping, not a time-valid roster. The workbook is a separate sample; its people are not silently merged into the SQL graph.</p>'),
('practice','Try it yourself',table(['Exercise','What to inspect'],[('Ask who manages Aspen Grove.','Find MANAGES and the account brief source.'),('Ask about CUS-001 A4 pricing with event date 2023-06-01.','Confirm contract dates, minimum quantity and product scope.'),('Change the event date to 2024-06-01.','Check which contract evidence is excluded.'),('Explore REP-100001, January 2018 in Finance explorer.','Compare actual, target, row count and [FINANCE] filters.'),('Ask for product-level sales totals.','The source does not contain those allocations; an answer should acknowledge that.'),('Open the Library.','Compare source origins and validity windows.')])+ '<p>When debugging, first inspect source IDs and paths, then the retrieval results, then the final answer. Model fluency is not evidence quality.</p>'),
('glossary','Glossary',GLOSSARY),('references','Continue learning',LINKS)])
